# Generated by Django 5.0.2 on 2024-03-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_cart',
            fields=[
                ('product_cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_cart_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('product_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_cart')),
            ],
        ),
    ]
